<a href="https://colab.research.google.com/github/Soham12Sawant/23102C0036_R_Programming/blob/main/2310C0036_R_Prog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = NA
is.na(x)

[1] TRUE

In [4]:
x = c(11,NA,13,NA)
is.na(x)
mean(x)
mean(x, na.rm =  TRUE)

[1] FALSE  TRUE FALSE  TRUE

[1] NA

[1] 12

In [6]:
which(is.na(x))
sum(is.na(x))

[1] 2 4

[1] 2

In [13]:
complete.cases(x)
y = na.omit(x)
y
attr(y,"na.action")
attr(y,"class")
mean(x)
mean(y)

[1]  TRUE FALSE  TRUE FALSE

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] 2 4
attr(,"class")
[1] "omit"

NULL

[1] NA

[1] 12

In [18]:
x = 5
if(x>4) x*3
if(x<4) x*4

[1] 15

In [21]:
if(x>3){
  print("The value is more than 3")
}
x = 2
if(x>3){
  print("The value is more than 3")
}

[1] "The value is more than 3"

In [22]:
x = 5
if ( x==3 ) { x = x-1 } else { x = 2*x }
x

[1] 10

In [24]:
 x= 3
if ( x==3 ) { x = x-1 } else { x = 2*x }
x

[1] 2

In [27]:
x = 5
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

x = 2
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

x = 3
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 10

[1] 7

[1] 2

In [29]:
x = 1:10
x
ifelse(x<6, x^2, x+1)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  4  9 16 25  7  8  9 10 11

In [30]:
x = c(7,8,9,4)
ifelse(x%%2 == 0, "even number","odd number")

[1] "odd number"  "even number" "odd number"  "even number"

In [33]:
switch(2, "apple","banana","orange")
switch(3, "apple","banana","orange")

[1] "banana"

[1] "orange"

In [38]:
switch("colour", "colour" = "blue", "gender" = "male", "volume" = "50")
switch("volume", "colour" = "blue", "gender" = "male", "volume" = "50")
switch("size", "colour" = "blue", "gender" = "male", "volume" = "50")

[1] "blue"

[1] "50"

In [42]:
 x = c(10,15,8,14,6,12)
 x
 which(x == 14)
 which(x != 8)
 which(x > 10)

[1] 10 15  8 14  6 12

[1] 4

[1] 1 2 4 5 6

[1] 2 4 6

In [47]:
x = matrix(nrow=3, ncol=3, data=1:9)
x
which.min(x)
which.max(x)
which(x %% 2 == 1)
which(x %% 2 == 1, arr.ind = TRUE)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

[1] 9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3